### ISSUE TITLE
Intermittent Exception While Working

### ISSUE THREAD

**Issue by tamimsalem** [Haacked/Encourage#12]
While working I get a random error, so far I couldn't figure out a scenario, here is the error window I get:

![encourage error](https://cloud.githubusercontent.com/assets/3831333/3441409/582c9898-0104-11e4-926e-cde71ca8b28b.png)

The log has the following entry for the error:

<entry>
    <record>801</record>
    <time>2014/07/01 09:37:05.314</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.&#x000D;&#x000A;Parameter name: index&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.NormalizedSnapshotSpanCollection.get_Item(Int32 index)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.Helpers.GetEncapsulatingSpan(ITextView textView, ITrackingSpan span1, ITrackingSpan span2)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultSignatureHelpPresenter.ComputePresentationSpan()&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultSignatureHelpPresenter.OnSessionSignaturesChanged(Object sender, NotifyCollectionChangedEventArgs e)&#x000D;&#x000A;   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)&#x000D;&#x000A;   at System.Collections.ObjectModel.ReadOnlyObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs args)&#x000D;&#x000A;   at System.Collections.ObjectModel.ReadOnlyObservableCollection`1.HandleCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)&#x000D;&#x000A;   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.BulkObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)&#x000D;&#x000A;   at System.Collections.ObjectModel.ObservableCollection`1.RemoveItem(Int32 index)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.BulkObservableCollection`1.RemoveItem(Int32 index)&#x000D;&#x000A;   at System.Collections.ObjectModel.Collection`1.Remove(T item)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.SignatureHelpSession.OnCaretPositionChanged(Object sender, CaretPositionChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
  </entry>

I hope this is enough to figure out the problem.

**Comment by Haacked** [comment]
I don't think this is due to Encourage. Going to close this.
