### ISSUE TITLE
Uses syntax highlighting?

### ISSUE THREAD

**Issue by jimgraham** [Haacked/Encourage#30]
One of my "discouragements" has the word `this` in it

![initialhighlight](https://cloud.githubusercontent.com/assets/430293/3895870/d8a7e54a-2251-11e4-871c-f16cc7739797.png)

when shown on top of a C# file, the discouragement seemed to have syntax highlighting. To confirm, I replaced my list of encouragements with nonsense that would syntax highlight

![testencouragelist](https://cloud.githubusercontent.com/assets/430293/3895871/d8ad1f7e-2251-11e4-8f46-a52628f9b7f7.png)

and they as well seem to syntax highlight.

![moresyntax](https://cloud.githubusercontent.com/assets/430293/3895869/d8a4b23a-2251-11e4-95a0-e56ab967ef3a.png)

Is this by design?

**Comment by Haacked** [comment]
I'm going to close this. If someone wants to submit a PR with an Adornment approach, I'd be all ears.
