### ISSUE TITLE
Encouragement displayed in Message window of SQL Query

### ISSUE THREAD

**Issue by HolisticDeveloper** [Haacked/Encourage#32]
Using VS 2013, I open a new query window from a Server Explorer data connection. When I execute the query, an encouragement is briefly displayed in the Message tab as the query is executed.

![image](https://cloud.githubusercontent.com/assets/7200095/4006081/b43d3bc2-29a1-11e4-8470-2d645daf5580.png)

**Comment by Haacked** [comment]
Ok, that seems weird. Not sure how to prevent that.

**Comment by Haacked** [comment]
I have no plans to fix this at this moment. I'd accept a PR if someone knows how to fix this.
