### ISSUE TITLE
Not working with Resharper :(

### ISSUE THREAD

**Issue by cavariux** [Haacked/Encourage#40]
It just doesn''t show anymore

**Comment by Haacked** [comment]
Did it used to work with R#? Which version of R# and VS does it not work with? Which version did it work with?

**Comment by CavariuX** [comment]
Sorry for not being precise with the information.
Visual Studio 2015 Update 4
Resharper C++ 2016.2
It works when I disable/uninstall Resharper but with it the message doesn't pop.
I'm not sure if it used to work with resharper.

**Comment by Haacked** [comment]
Hmm, anyone else have this problem?

**Comment by silkfire** [comment]
I think I might have the very same problem, as the extension doesn't work in neither 2015 or 2017, both have ReSharper installed. 

It only works with .js files, that's what I've discovered so far.

**Comment by silkfire** [comment]
@Haacked Any update on this issue?

**Comment by Haacked** [comment]
I don't have Resharper right now. Can you try pulling the source code for this extension and stepping through it to see if anything pops up?

**Comment by silkfire** [comment]
@Haacked I have no idea how to do that, have never debugged extensions before :)

**Comment by silkfire** [comment]
@Haacked You can download the trial of ReSharper, it's free for 30 days.

**Comment by Haacked** [comment]
I just don't have the bandwidth to fix this. If more people complain, I'll look into it.
