### ISSUE TITLE
Add Icon for the Marketplace

### ISSUE THREAD

**Issue by rprouse** [Haacked/Encourage#42]
This VSIX doesn't have an icon displayed in the marketplace. The icon should be 90x90.

![image](https://cloud.githubusercontent.com/assets/493828/24073317/3bf405be-0bcc-11e7-981a-7a867285dea7.png)

The icon is added to the metadata section of the vsixmanifest, here is the line from the NUnit adapter,

```xml
<Icon>nunit_90.png</Icon>
```

In the CSPROJ, the icon should be set to `IncludeInVsix=true`

You can set a 200x200 preview image the same way, but it isn't displayed in VS2017 anymore, just previous versions.

Any ideas for an icon? Speech bubble with an exclamation point?

**Comment by Haacked** [comment]
> Any ideas for an icon? Speech bubble with an exclamation point?

Hmm, how about a big thumbs up? Or a smiley with a thumbs up. But it can't be a copyrighted emoji.

**Comment by rprouse** [comment]
I did a quick search for CC thumbs up and only found one decent one, https://www.iconfinder.com/icons/383996/approve_best_hand_like_thumbs_up_yes_icon#size=128

![image](https://cloud.githubusercontent.com/assets/493828/25256068/3b40c018-25fc-11e7-969f-2efe02401b09.png)

My kingdom for a graphics artist! 😄

**Comment by Haacked** [comment]
<img src="https://cloud.githubusercontent.com/assets/19977/25256649/3649b642-25e7-11e7-8cba-c88d9c94aa5f.png" width="60" /> I found this one. I think I like yours better.
