### ISSUE TITLE
Support for VS2013?

### ISSUE THREAD

**Issue by baidarka** [Haacked/Encourage#46]
Encourage, what a sweet extension.
Tried to install on 'Microsoft Visual Studio Ultimate 2013'. Got 'VSIXInstaller.NoApplicableSKUsException'.
The logfile explains that supported products are 'Microsoft.VisualStudio.Community [11.0,15.0]', and thus I am out of luck. Is this by design or would you be willing to fix this? Thank so much in advance! Way to go!! :)

[VSIXInstaller_log.txt](https://github.com/Haacked/Encourage/files/1022403/VSIXInstaller_log.txt)

**Comment by Haacked** [comment]
> Is this by design or would you be willing to fix this?

It's because I don't run VS 2013 any more and don't have the bandwidth to make it work or test it on 2013. If you're willing to help, I'd accept the PR!
