### ISSUE TITLE
Not installing in VS 2017

### ISSUE THREAD

**Issue by AlexYFil** [haacked/Encourage#48]
VS 2017 Enterprise (ver 15.4.4)
Error and log for it attached

![image](https://user-images.githubusercontent.com/34034603/33274549-6764ae90-d3a1-11e7-80d3-2b7c76c28c88.png)

27.11.2017 18:33:33 - Microsoft VSIX Installer
27.11.2017 18:33:33 - -------------------------------------------
27.11.2017 18:33:33 - Initializing Install...
27.11.2017 18:33:33 - Extension Details...
27.11.2017 18:33:33 - 	Identifier      : f38d29e7-cd86-43d5-9c32-4be26302b55e
27.11.2017 18:33:33 - 	Name            : Encourage
27.11.2017 18:33:33 - 	Author          : Phil Haack
27.11.2017 18:33:33 - 	Version         : 1.2.1
27.11.2017 18:33:33 - 	Description     : Adds a bit of whimsy to your work day.
27.11.2017 18:33:33 - 	Locale          : en-US
27.11.2017 18:33:33 - 	MoreInfoURL     : https://github.com/haacked/encourage
27.11.2017 18:33:33 - 	InstalledByMSI  : False
27.11.2017 18:33:33 - 	SupportedFrameworkVersionRange : [4.5,)
27.11.2017 18:33:33 - 
27.11.2017 18:33:33 - 	Supported Products : 
27.11.2017 18:33:33 - 		Microsoft.VisualStudio.Community
27.11.2017 18:33:33 - 			Version : [11.0,15.0]
27.11.2017 18:33:33 - 
27.11.2017 18:33:33 - 	References      : 
27.11.2017 18:33:33 - 		-------------------------------------------------------
27.11.2017 18:33:33 - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
27.11.2017 18:33:33 - 		Name         : Visual Studio MPF 11.0
27.11.2017 18:33:33 - 		Version      : [11.0]
27.11.2017 18:33:33 - 		MoreInfoURL  : 
27.11.2017 18:33:33 - 		Nested       : No
27.11.2017 18:33:33 - 
27.11.2017 18:33:33 - 
27.11.2017 18:33:33 - Searching for applicable products...
27.11.2017 18:33:33 - Found installed product - Global Location
27.11.2017 18:33:33 - Found installed product - ssms
27.11.2017 18:33:33 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   в VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   в VSIXInstaller.App.InitializeInstall()
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()

**Comment by Haacked** [comment]
Thanks for the report. What edition of Visual Studio 2017 are you running?

**Comment by balassy** [comment]
I could successfully install this extension today for VS 2017 Enterprise. Thanks for creating it, Phil!
