### ISSUE TITLE
Not working in visual studio 2017

### ISSUE THREAD

**Issue by Stegnerd** [haacked/Encourage#49]
I saw the closed ticket: https://github.com/Haacked/Encourage/issues/40 and it was closed because someone didn't want to test with resharper. I can confirm that with resharper ultimate that it does not work on files like .cs or .cshtml. I did notice that it worked in a web.config file however. I am also using visual studio 2017 15.7.4 on windows 10 and resharper JetBrains ReSharper Ultimate 2018.1.2 Build 112.0.20180530.113618

I would be interested in investigating this further!

**Comment by Haacked** [comment]
> I would be interested in investigating this further!

I welcome the help!

**Comment by Stegnerd** [comment]
I had to do a fresh install, using the same versions and had no problems with it this time. Must have been external factors. Sorry!
