### ISSUE TITLE
Build & Stage Artifacts using GitHub Actions

### ISSUE THREAD

**Issue by CalvinAllen** [haacked/Encourage#54]
Curious if you'd want something like this - I started to add it with the other PR but then realized that was a bad idea :)

I have some pre-existing art for doing it if interested.

**Comment by haacked** [comment]
Yes! This would make it easier for me to publish.

**Comment by CalvinAllen** [comment]
@haacked How do you like to do versioning?  I don't follow SemVer in my extensions, and just use dates / build numbers, so my "art" is based on that, but it could be changed pretty easily to something else like a specific tag push, etc.

**Comment by haacked** [comment]
I usually do Semver but I’m fine with whatever is easiest for you

**Comment by CalvinAllen** [comment]
Cool - I'll see what I can get working.  Worse case scenario, push a tag with the version number in it, and we can just use that straight from the tag.

**Comment by haacked** [comment]
That works for me since I tag releases this way already.

**Comment by CalvinAllen** [comment]
Haven't forgotten about this - planning to do this in the next couple weeks when I have some time off from work :)
